# Generated by Django 3.1.1 on 2020-09-29 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sport_events', '0012_auto_20200925_1417'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_type', models.CharField(max_length=8)),
                ('bet_code', models.CharField(max_length=32)),
                ('win_coefficient', models.DecimalField(decimal_places=3, max_digits=6)),
                ('user_bet', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user_win', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_went', models.BooleanField(default=None, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('events', models.ManyToManyField(to='sport_events.MatchEvent')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport_events.match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
