# Generated by Django 3.1.1 on 2020-09-30 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_bet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbet',
            name='match',
        ),
        migrations.AddField(
            model_name='userbet',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userbet',
            name='bet_code',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
