# Generated by Django 3.1.1 on 2020-09-15 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatchEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oc_group_name', models.CharField(max_length=255)),
                ('oc_name', models.CharField(max_length=255)),
                ('oc_rate', models.DecimalField(decimal_places=5, max_digits=9)),
                ('oc_pointer', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='t_country', to='sport_events.sport')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='t_sport', to='sport_events.sport')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField()),
                ('game_num', models.IntegerField()),
                ('uniq', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
                ('game_start', models.DateTimeField()),
                ('opp_1_name', models.CharField(max_length=255)),
                ('opp_2_name', models.CharField(max_length=255)),
                ('opp_1_id', models.IntegerField()),
                ('opp_2_id', models.IntegerField()),
                ('events', models.ManyToManyField(to='sport_events.MatchEvent')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport_events.sport')),
            ],
        ),
    ]
