# Generated by Django 3.1.1 on 2020-09-15 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport_events', '0002_remove_match_api_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='sport',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='m_sport', to='sport_events.sport'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='m_tournament', to='sport_events.tournament'),
            preserve_default=False,
        ),
    ]
