# Generated by Django 3.1.1 on 2020-09-15 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport_events', '0003_auto_20200915_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='t_country', to='sport_events.country'),
        ),
    ]
