# Generated by Django 3.1.1 on 2020-09-21 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_events', '0004_auto_20200915_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='deleted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='match',
            name='deleted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='match',
            name='request_type',
            field=models.CharField(default='line', max_length=4),
        ),
        migrations.AddField(
            model_name='matchevent',
            name='deleted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sport',
            name='deleted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='deleted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='request_type',
            field=models.CharField(default='line', max_length=4),
        ),
    ]
