# Generated by Django 3.1.1 on 2020-09-21 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_events', '0006_auto_20200921_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='request_type',
            field=models.CharField(default='line', max_length=4),
        ),
        migrations.AddField(
            model_name='sport',
            name='request_type',
            field=models.CharField(default='line', max_length=4),
        ),
    ]
