# Generated by Django 3.1.1 on 2020-09-21 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_events', '0008_auto_20200921_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='ended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='game_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='match',
            name='score_full',
            field=models.CharField(max_length=20),
        ),
    ]
