# Generated by Django 3.1.1 on 2020-10-03 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_events', '0012_auto_20200925_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='admin_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='matchevent',
            name='admin_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='match',
            name='opp_1_icon',
            field=models.URLField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='opp_1_id',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='opp_2_icon',
            field=models.URLField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='opp_2_id',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='period_name',
            field=models.CharField(default='line', max_length=20),
        ),
        migrations.AlterField(
            model_name='match',
            name='score_full',
            field=models.CharField(default='0:0', max_length=20),
        ),
        migrations.AlterField(
            model_name='match',
            name='score_period',
            field=models.CharField(default='0:0', max_length=10),
        ),
    ]
