# Generated by Django 3.1.1 on 2020-10-07 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_events', '0013_auto_20201003_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchevent',
            name='oc_rate',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
