# Generated by Django 3.1.1 on 2020-10-08 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport_events', '0015_auto_20201008_0026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ('game_start', 'deleted'), 'verbose_name': 'Матч', 'verbose_name_plural': 'Матчи'},
        ),
    ]
