# Generated by Django 3.1.1 on 2020-10-08 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport_events', '0016_auto_20201008_1832'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['deleted', '-game_start'], 'verbose_name': 'Матч', 'verbose_name_plural': 'Матчи'},
        ),
        migrations.CreateModel(
            name='MatchAdminResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner', models.CharField(choices=[('П1', 'П1'), ('П2', 'П2'), ('X', 'X')], max_length=2)),
                ('total', models.CharField(choices=[('Б', 'Б'), ('М', 'М')], max_length=1)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport_events.match')),
            ],
        ),
    ]
