# Generated by Django 3.1.1 on 2020-10-08 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport_events', '0017_auto_20201008_2108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchadminresult',
            options={'ordering': ['match'], 'verbose_name': 'Результат матча, созданный админом', 'verbose_name_plural': 'Результаты матчей, созданные админом'},
        ),
    ]
