# Generated by Django 3.1.1 on 2020-10-13 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_events', '0018_auto_20201008_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchadminresult',
            name='date_closed',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='matchevent',
            name='short_name',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
    ]
