# Generated by Django 3.1.1 on 2020-10-14 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_events', '0019_auto_20201014_0220'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='uniq',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='game_id',
            field=models.IntegerField(unique=True, verbose_name='Id'),
        ),
        migrations.AlterField(
            model_name='match',
            name='game_num',
            field=models.IntegerField(unique=True, verbose_name='Номер игры'),
        ),
    ]
