# Generated by Django 3.1.1 on 2020-10-19 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_events', '0020_auto_20201015_0205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['game_id'], 'verbose_name': 'Матч', 'verbose_name_plural': 'Матчи'},
        ),
        migrations.AddField(
            model_name='matchevent',
            name='last_changed',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Последнее изменение'),
        ),
        migrations.AlterField(
            model_name='match',
            name='game_id',
            field=models.IntegerField(null=True, verbose_name='Id'),
        ),
        migrations.AlterField(
            model_name='match',
            name='game_num',
            field=models.IntegerField(null=True, verbose_name='Номер игры'),
        ),
        migrations.AlterField(
            model_name='match',
            name='period_name',
            field=models.CharField(default='line', max_length=50, verbose_name='Текущий период'),
        ),
        migrations.AlterField(
            model_name='match',
            name='score_full',
            field=models.CharField(default='0:0', max_length=50, verbose_name='Полный счет'),
        ),
        migrations.AlterField(
            model_name='match',
            name='score_period',
            field=models.CharField(default='0:0', max_length=50, verbose_name='Счет по периодам'),
        ),
    ]
